---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot
spec:
  type: LoadBalancer
  selector:
    app: spring-boot
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  labels:
    app: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - name: spring-boot
        image: asia-southeast1-docker.pkg.dev/GOOGLE_PROJECT/vttp-project/test:latest
        ports:
          - containerPort: 8080