#
# First stage
#

FROM maven:3.8.3-openjdk-17 AS build

COPY src /home/app/src
COPY pom.xml /home/app

ARG SQL_URL
ARG SQL_USER
ARG SQL_PASSWORD
ARG S3_ACCESSKEY
ARG S3_SECRETKEY
ARG S3_BUCKETURL
ARG JWT_SECRETKEY

RUN mvn -f /home/app/pom.xml clean package

#
# second stage
#

FROM openjdk:17-oracle

COPY --from=build /home/app/target/vttp-project-0.0.1-SNAPSHOT.jar /usr/local/lib/vttp-project-0.0.1.jar

# RUN --mount=type=secret,id=SQL_URL \
#   --mount=type=secret,id=SQL_USER \
#    export SQL_URL=$(cat /run/secrets/SQL_URL) && \
#    export SQL_USER=$(cat /run/secrets/SQL_USER) && \
#    echo $SQL_URL

ARG SQL_URL
ARG SQL_USER
ARG SQL_PASSWORD
ARG S3_ACCESSKEY
ARG S3_SECRETKEY
ARG S3_BUCKETURL
ARG JWT_SECRETKEY

ENV PORT=8080
ENV SQL_URL=${SQL_URL}
ENV SQL_USER=${SQL_USER}
ENV SQL_PASSWORD=${SQL_PASSWORD}
ENV S3_ACCESSKEY=${S3_ACCESSKEY}
ENV S3_SECRETKEY=${S3_SECRETKEY}
ENV S3_BUCKETURL=${S3_BUCKETURL}
ENV JWT_SECRETKEY=${JWT_SECRETKEY}

EXPOSE ${PORT}
ENTRYPOINT ["java", "-jar", "/usr/local/lib/vttp-project-0.0.1.jar"]
