name: Deploy on GKE

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_ID_PROVIDER }}
        service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: build and push docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev
        docker build -t asia-southeast1-docker.pkg.dev/$GOOGLE_PROJECT/vttp-project/test:latest .
        docker push asia-southeast1-docker.pkg.dev/$GOOGLE_PROJECT/vttp-project/test:latest
