name: Deploy on GKE

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    - name: code checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: setup-gke-gcloud-auth-plugin
      uses: simenandre/setup-gke-gcloud-auth-plugin@v1.1.2
            
    # - name: 'Set up Cloud SDK'
      # uses: 'google-github-actions/setup-gcloud@v1'
      #   with:
      #     install_component: 'gke-gcloud-auth-plugin'
        
    - name: build and push docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev
        docker build -t asia-southeast1-docker.pkg.dev/$GOOGLE_PROJECT/vttp-project/test:v1.0 . --build-arg="SQL_URL=${{ secrets.SQL_URL }}" --build-arg="SQL_USER=${{ secrets.SQL_USER }}" --build-arg="SQL_PASSWORD=${{ secrets.SQL_PASSWORD }}" --build-arg="S3_ACCESSKEY=${{ secrets.S3_ACCESSKEY }}" --build-arg="S3_SECRETKEY=${{ secrets.S3_SECRETKEY }}" --build-arg="S3_BUCKETURL=${{ secrets.S3_BUCKETURL }}" --build-arg="JWT_SECRETKEY=${{ secrets.JWT_SECRETKEY }}"
        docker push asia-southeast1-docker.pkg.dev/$GOOGLE_PROJECT/vttp-project/test:v1.0
    
    - name: deploy to gke
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud container clusters get-credentials vttp-cluster --region asia-southeast1-a
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" resources.yaml
        kubectl apply -f resources.yaml

